[development]
address = "localhost"
port = 80
log = "normal"

[staging]
address = "0.0.0.0"
port = 80
log = "normal"

[production]
address = "0.0.0.0"
port = 80
log = "critical"

[global]
address = "127.0.0.1"
port = 8082
